baseURL = 'https://pjesus-pastorm.github.io/algoritmia/'
languageCode = 'es'
title = 'Sitio sobre algoritmia'
theme= 'tale'

[menu]
	[[menu.main]]
		identifier = "introducción"
		name = "introduccion"
		title = "Introducción"
		url ="/introduccion/"
		weight = 0
	